# ==========================================
# ECHO - Discovery Service
# ==========================================

# Server
server.port=8761

# Application
spring.application.name=discovery-service

# ==========================================
# Eureka Server
# ==========================================

# Discovery server does not register itself
eureka.client.register-with-eureka=false

# Discovery server does not need to fetch a registry
eureka.client.fetch-registry=false

# Start without waiting for other Eureka peers
eureka.server.wait-time-in-ms-when-sync-empty=0